name: validation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Validation
      run: python3 ./validate_packages_and_resources.py
    - name: Generate index
      run: python3 ./tools/generate_index.py
    - name: Commit and push new index.json
      run: |
        git config --global user.name "Github action"
        git config --global user.email "carles@pina.cat"
        git add index.json
        git commit -m 'Automatic update of the index.json' && git push || true

